### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by ZilinIB** [cknabs/RIAI-summary-HS2020#1]
Thanks for sharing the summary! It helped me a lot. I've noticed two typos though:
1. In Section Adversarial attack, Relaxed:  the absolute sign in the expression of L(eta) is misplaced:  correction follows
When using $L_\infty$, gradient of $\|\eta\|_\infty$ is zero at all non-max entries $\rightarrow$ use $L(\eta) = \sum_i \max(0, \lvert \eta_i \rvert - \tau )$ instead; Start with $\tau=1$, update $\eta$ $K$ times, if $L(\eta) = 0$ decrease $\tau$ and repeat, otherwise stop and return previous $\eta$.

2. In section Geometric transformation, MVTh: in the last inequality, the parenthesis is misplaced, correction follows
\paragraph{$\rightarrow$ MVTh} if $\lvert \partial_i f(\kappa') \rvert \le \lvert L_i \rvert \forall \kappa' \in D = [h_l, h_u]$
$f(\kappa) = f(\kappa_C) + \nabla f(\kappa')^T(\kappa-\kappa_C) \le f(\kappa_C) + \lvert L \rvert^T (\kappa - \kappa_C) \le f\left(\frac{h_u+h_l}{2}\right) + \lvert L \rvert^T \frac{(h_u-h_l)}{2}$

**Comment by cknabs** [comment]
Thanks a lot for opening the issue, nice catch!
Don't hesitate to let me know if you find any other problems (even after the exam), I'll make sure to fix them.

**Comment by ZilinIB** [comment]
No Problem! Good luck with the exam:)
